### ISSUE TITLE
Minor bugfix obfuscated by transpilation

### ISSUE THREAD

**Issue by davidporter-id-au** [CascadeEnergy/dynamoDb-marshaler#13]
I found that dynamodb wasn't allowing string arrays which included empty strings and breaking (the data I have to work with is somewhat chaotic).
```
["foo", ""] -> {"SS": ["foo", ""] } //apparently breaks Dynamo
```
I've patched it simply by filtering out empty strings on string arrays, but I'm worried that there must be a diff with our babel minor versions or something because the diff is huge. Would you still want a PR or is there something else I can do to make this a nicer PR?

**Comment by davidporter-id-au** [comment]
Coincidentally, the diff is [here](https://github.com/davidporter-id-au/dynamoDb-marshaler/commit/d700672d8361b8b7df4b79ae58307f48e48a764d)

**Comment by nackjicholson** [comment]
Hi @davidporter-id-au this is a known issue, and I believe the error is intentional because it does break dynamo to store an empty string. It is mentioned in the [README](https://github.com/CascadeEnergy/dynamoDb-marshaler#empty-strings) in fact. I don't want to simply filter the empty strings out, because that might end up being very confusing if the marshaler altered your data set. You should prepare your data to be saved to dynamo before marshaling.

Thanks for raising the issue, it is confusing and kind of a bummer that dynamo behaves this way.

**Comment by nackjicholson** [comment]
@jinsyaoommen I don't have administrator access to this project after all. Can't close this issue. When you have a chance can you do it. Also, feel free to give me admin powers if you want.

**Comment by davidporter-id-au** [comment]
Fair call, I'll see if I can find an object cleaner which does the job.
