### ISSUE TITLE
default value for empty strings

### ISSUE THREAD

**Issue by sorenbs** [CascadeEnergy/dynamoDb-marshaler#2]
DynamoDb does not accept empty strings and simply throws an error.

Would it make sense for the marshaler to replace empty strings with null? Perhaps make it configurable what value should be substituted for empty strings.

**Comment by sorenbs** [comment]
Thanks Will, sorry I didn't get beck to you earlier.

This is an improvement and I have been using it in production since January. 

I understand your desire to keep this project strictly focused on marshalling, but as you stated having to prune out empty strings is a small inconvenience, but something that is easily forgotten. For now I have created a wrapper around the marshaller to handle this.

Another thing I came across is that storing null values for an indexed property is not allowed (gives the error below) whereas completely omitting the property is valid and simply omits the object from the index.

message: 'One or more parameter values were invalid: Type mismatch for Index Key webshopId Expected: S Actual: NULL IndexName: webshopId-created-index'

So, if you have an index on p:
save({id: 1, p: null}) // Not allowed
save({id: 1}) // Perfectly fine

Again, I handle this by wrapping the marshaller and simply removing all null properties. This gives me essentially the same behaviour as MongoDB exhibits which I find to be a good balance.

Have you had a chance to think more about this?

**Comment by nackjicholson** [comment]
Hey @sorenbs thanks for using this! In production no less! I don't know if you saw above, but I made a PR #3 to throw a marshaling error for `""`. In thinking about it more and more, and being brought other issues in the same vain (#5, #6), I think I'm reinforcing my understanding that DynamoDb has a set of rules about data operation that are outside the scope of marshaling.

The tricky thing about your example with the saving of a `null` index attribute, is that to address it with this library it would require this library to know that `p` is used by an index. This project is strictly about translation -- when it sees `{p: null}` it is going to turn it into `{p: {NULL: true}}` every time, that is it's job regardless of `p`'s significance.

I think you did the right thing making a wrapper tool to "groom"/"validate" your objects before saving. If you're working with data that doesn't always adhere to DynamoDb's rules, you gotta get in there and shuffle things around. I think there is space for another single-responsibility npm module `dynamodb-validator`/`dynamodb-groomer`. I think it might be kind of useful to have a project which you do configure with some information about your schema, and then it inspects your objects and cleans them up if it can, or throws an error.

If you have the time and energy, I would be willing to help you with that project. Cheers!

BTW since you're using this in production, take a look at the README.md in #6 because it has some docs that explain the jump from `v0.1.1` to `v1.0.0` in the way JS Arrays are marshaled to Dynamo Lists and Sets.

**Comment by bilal-fazlani** [comment]
I just want to say what I think from the perspective of a developer who downloads and uses this library.
 
This isn't just a marshaller. It's **DynamoDb marshaller**. And as a developer, when I download this package, use it to marshal a javascript object or a json string, I just expect it to work and give me a perfectly valid marshalled json or object **that is compatible with DynamoDb**. 

**As a user of this library, I don't really care if it breaks single responsibility principle to do what it's supposed to do.** If I want to convert an object/json into dynamoDb format and I download this library, and it crashes if my object contains empty strings, believe me that's not a good feeling. it just feels **incomplete**. 

If I have to download another package that will validate or process the marshalled json, or if I have to write that code myself to replace empty strings with nulls, that's just not good. 

You see, when I give give this library an object which contains properties that have empty string values, that's not an invalid object. That is a perfectly valid object. **The fact that dynamoDb doesn't accept empty string doesn't make my object "invalid".** So marshaller shouldn't be throwing exceptions when it finds such object. Neither should it return a marshalled json that has empty strings, because that would be invalid "marshalled json". 
I guess, all I am saying is, I expect a valid marshalled json that is compatible with dynamodb when I use this library. And if this library has to anything it needs to to make it happen, it should do it - instead of telling the developers that their object contains empty strings and then blowing up the application. Because this is a **dynamodb** marshaller.

We should atleast make it configurable so that users will have a choice. If they want an exception, they can have it. I would then just configure the marshaller to do the magic. I am sure many others will do the same. And eventually we will have to make it default.

**Comment by nackjicholson** [comment]
Fair enough, it seems this module does not do what you think it is supposed to do, and that's not good.

Would you like it to marshal an empty string to `{ NULL: true }`? I think that will in turn create another problem for people who weren't expecting null's in their DynamoDb tables for every empty string they sent it. I do not see a clear path to getting it to do what you want without causing more issues. The code is licensed under MIT, and is therefore available to you in any capacity. You can rip it off directly and redistribute it with alterations. You can also make a PR for consideration if you'd like to see these changes as a part of this project.

I'm sure DynamoDb has an excellent reason for not accepting empty strings and making their API only accept these formatted objects, but that was a decision made by Amazon, not this module author. As a fellow user of this module frustrated by the amount of work there is to do in order to make JSON data acceptable to DynamoDb -- believe me I sympathize.

(I hear they have their own marshaler as part of the SDK these days, please look into it because it may solve more for you).

I do not speak for CascadeEnergy and my opinion does not necessarily represent theirs.
