### ISSUE TITLE
Optionally use list type for ordered string/number arrays 

### ISSUE THREAD

**Issue by rbickham11** [CascadeEnergy/dynamoDb-marshaler#20]
Hello!

Really appreciating this library as it has saved me lots of time. However, I ran into a potential edge case when I realized that the order of my array was being changed when I inserted it into Dynamo. As stated [here](https://github.com/CascadeEnergy/dynamoDb-marshaler#understanding-the-rules) a String Set type will be used for an array of unique values, however Dynamo does not preserve order for sets.

I have a case where I need an ordered list of strings, so the List type would need to be used. Could this potentially be an option/configuration somewhere? Also to note is that the default in the DynamoDB console when an array is created in JSON view is to create a list.

**Comment by nwarlen** [comment]
Thanks for the issue. 

I would like to direct you to the [Official Document Client](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html), because I believe it has the behavior you are after. 

We are choosing not to change this library so as to support legacy systems, which may rely on the current behavior.

If you have any other questions or would like any clarification, please do not hesitate to contact us via this issue. 

If you find the provided documentation helpful, feel free to close this issue.

Thanks

**Comment by rbickham11** [comment]
Thanks for the reference, I was not aware of this. 

Thank you for your quick reply!
